// ********RoostGPT********
/*
Test generated by RoostGPT for test mayankzbio-go-clean using AI Type Claude AI and AI Model claude-3-5-sonnet-20240620

ROOST_METHOD_HASH=Output_b4dd5ccd4f
ROOST_METHOD_SIG_HASH=Output_639eeea89e

FUNCTION_DEF=func (c createTransferPresenter) Output(transfer domain.Transfer) usecase.CreateTransferOutput
Based on the provided function and context, here are several test scenarios for the `Output` method of the `createTransferPresenter` struct:

```
Scenario 1: Valid Transfer Output

Details:
  Description: Test that the Output method correctly transforms a valid domain.Transfer object into a usecase.CreateTransferOutput object.

Execution:
  Arrange:
    - Create a mock domain.Transfer object with valid data for all fields.
    - Initialize a createTransferPresenter instance.
  Act:
    - Call the Output method with the mock Transfer object.
  Assert:
    - Verify that the returned CreateTransferOutput object has all fields correctly mapped from the input Transfer object.
    - Check that the ID, AccountOriginID, and AccountDestinationID are correctly converted to strings.
    - Ensure the Amount is correctly converted to float64.
    - Confirm the CreatedAt is formatted according to RFC3339.

Validation:
  This test ensures that the presenter correctly transforms the domain object into the expected output format. It's crucial for maintaining the contract between the domain layer and the use case layer, ensuring data integrity and proper formatting for client consumption.

Scenario 2: Zero Amount Transfer

Details:
  Description: Test the Output method's behavior when processing a Transfer with a zero amount.

Execution:
  Arrange:
    - Create a mock domain.Transfer object with an amount of zero.
    - Initialize a createTransferPresenter instance.
  Act:
    - Call the Output method with the zero-amount Transfer object.
  Assert:
    - Verify that the returned CreateTransferOutput object has an Amount field of exactly 0.0.
    - Check that all other fields are correctly mapped.

Validation:
  This test is important to ensure that the presenter handles edge cases correctly, particularly zero-value amounts which might be treated differently in some systems. It validates that the presenter doesn't alter or reject valid zero-amount transfers.

Scenario 3: Maximum Precision Amount

Details:
  Description: Test the Output method's handling of a Transfer with a very precise (many decimal places) amount.

Execution:
  Arrange:
    - Create a mock domain.Transfer object with a high-precision amount (e.g., 100.123456789).
    - Initialize a createTransferPresenter instance.
  Act:
    - Call the Output method with the high-precision Transfer object.
  Assert:
    - Verify that the returned CreateTransferOutput object's Amount field maintains the full precision of the input.
    - Check that all other fields are correctly mapped.

Validation:
  This test ensures that the presenter maintains numerical precision when converting amounts. It's crucial for financial applications where even small discrepancies can lead to significant issues over time or in large-scale operations.

Scenario 4: Far Future CreatedAt Date

Details:
  Description: Test the Output method's handling of a Transfer with a far future creation date.

Execution:
  Arrange:
    - Create a mock domain.Transfer object with a CreatedAt time set to a far future date (e.g., year 9999).
    - Initialize a createTransferPresenter instance.
  Act:
    - Call the Output method with the future-dated Transfer object.
  Assert:
    - Verify that the returned CreateTransferOutput object's CreatedAt field is correctly formatted according to RFC3339, despite the unusual date.
    - Check that all other fields are correctly mapped.

Validation:
  This test verifies the presenter's ability to handle extreme time values, ensuring that date formatting remains consistent and correct even for unusual scenarios. It's important for maintaining data integrity and preventing potential issues with time-based operations or display.

Scenario 5: Identical Origin and Destination Accounts

Details:
  Description: Test the Output method's behavior when the Transfer has the same account for both origin and destination.

Execution:
  Arrange:
    - Create a mock domain.Transfer object where AccountOriginID and AccountDestinationID are the same.
    - Initialize a createTransferPresenter instance.
  Act:
    - Call the Output method with the same-account Transfer object.
  Assert:
    - Verify that the returned CreateTransferOutput object correctly reflects the identical AccountOriginID and AccountDestinationID.
    - Check that all other fields are correctly mapped.

Validation:
  This test ensures that the presenter correctly handles and represents transfers within the same account, which might be a valid use case in some systems. It verifies that the presenter doesn't alter or reject such transfers, maintaining data fidelity.
```

These scenarios cover various aspects of the `Output` method's functionality, including normal operation, edge cases with amounts and dates, and potential special cases like same-account transfers. They aim to ensure the robustness and correctness of the presenter's output transformation across different input scenarios.
*/

// ********RoostGPT********
package presenter

import (
	"testing"
	"time"

	"github.com/gsabadini/go-clean-architecture/domain"
	"github.com/gsabadini/go-clean-architecture/usecase"
)

func TestcreateTransferPresenterOutput(t *testing.T) {
	tests := []struct {
		name     string
		transfer domain.Transfer
		want     usecase.CreateTransferOutput
	}{
		{
			name: "Valid Transfer Output",
			transfer: createTransfer(
				"transfer123",
				"origin456",
				"dest789",
				100.50,
				time.Date(2023, 5, 15, 10, 30, 0, 0, time.UTC),
			),
			want: usecase.CreateTransferOutput{
				ID:                   "transfer123",
				AccountOriginID:      "origin456",
				AccountDestinationID: "dest789",
				Amount:               100.50,
				CreatedAt:            "2023-05-15T10:30:00Z",
			},
		},
		{
			name: "Zero Amount Transfer",
			transfer: createTransfer(
				"transfer000",
				"origin111",
				"dest222",
				0,
				time.Date(2023, 5, 16, 11, 45, 0, 0, time.UTC),
			),
			want: usecase.CreateTransferOutput{
				ID:                   "transfer000",
				AccountOriginID:      "origin111",
				AccountDestinationID: "dest222",
				Amount:               0.0,
				CreatedAt:            "2023-05-16T11:45:00Z",
			},
		},
		{
			name: "Maximum Precision Amount",
			transfer: createTransfer(
				"transfer999",
				"origin888",
				"dest777",
				100.123456789,
				time.Date(2023, 5, 17, 14, 20, 0, 0, time.UTC),
			),
			want: usecase.CreateTransferOutput{
				ID:                   "transfer999",
				AccountOriginID:      "origin888",
				AccountDestinationID: "dest777",
				Amount:               100.123456789,
				CreatedAt:            "2023-05-17T14:20:00Z",
			},
		},
		{
			name: "Far Future CreatedAt Date",
			transfer: createTransfer(
				"transferFuture",
				"originFuture",
				"destFuture",
				1000.00,
				time.Date(9999, 12, 31, 23, 59, 59, 0, time.UTC),
			),
			want: usecase.CreateTransferOutput{
				ID:                   "transferFuture",
				AccountOriginID:      "originFuture",
				AccountDestinationID: "destFuture",
				Amount:               1000.00,
				CreatedAt:            "9999-12-31T23:59:59Z",
			},
		},
		{
			name: "Identical Origin and Destination Accounts",
			transfer: createTransfer(
				"transferSame",
				"sameAccount",
				"sameAccount",
				50.75,
				time.Date(2023, 5, 18, 9, 0, 0, 0, time.UTC),
			),
			want: usecase.CreateTransferOutput{
				ID:                   "transferSame",
				AccountOriginID:      "sameAccount",
				AccountDestinationID: "sameAccount",
				Amount:               50.75,
				CreatedAt:            "2023-05-18T09:00:00Z",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			c := createTransferPresenter{}
			got := c.Output(tt.transfer)
			if got != tt.want {
				t.Errorf("createTransferPresenter.Output() = %v, want %v", got, tt.want)
			}
		})
	}
}

// Helper function to create a domain.Transfer object
func createTransfer(id, originID, destID string, amount float64, createdAt time.Time) domain.Transfer {
	return domain.Transfer{
		ID:                   domain.TransferID(id),
		AccountOriginID:      domain.AccountID(originID),
		AccountDestinationID: domain.AccountID(destID),
		Amount:               domain.Money(amount * 100), // Convert to cents
		CreatedAt:            createdAt,
	}
}
