// ********RoostGPT********
/*
Test generated by RoostGPT for test mayankzbio-go-clean using AI Type Claude AI and AI Model claude-3-5-sonnet-20240620

ROOST_METHOD_HASH=Output_176178cc60
ROOST_METHOD_SIG_HASH=Output_d83d35060a

FUNCTION_DEF=func (a createAccountPresenter) Output(account domain.Account) usecase.CreateAccountOutput
Based on the provided function and context, here are several test scenarios for the `Output` method of the `createAccountPresenter` struct:

```
Scenario 1: Valid Account Conversion

Details:
  Description: Test that the Output method correctly converts a domain.Account to a usecase.CreateAccountOutput with all fields properly mapped.
Execution:
  Arrange: Create a domain.Account with known values for all fields.
  Act: Call the Output method of createAccountPresenter with the created account.
  Assert: Verify that the returned CreateAccountOutput has all fields matching the input account's data.
Validation:
  This test ensures that the basic functionality of the Output method works as expected, correctly mapping all fields from the domain model to the use case output. It's crucial for maintaining the integrity of data as it moves through different layers of the application.

Scenario 2: Zero Balance Account

Details:
  Description: Verify that an account with a zero balance is correctly represented in the output.
Execution:
  Arrange: Create a domain.Account with a balance of 0.
  Act: Call the Output method with this account.
  Assert: Check that the Balance field in the output is exactly 0.0.
Validation:
  This test is important to ensure that zero balances are handled correctly and not rounded or misrepresented, which could be critical for financial accuracy.

Scenario 3: Maximum Precision Balance

Details:
  Description: Test the handling of an account with a balance that uses the maximum precision of float64.
Execution:
  Arrange: Create a domain.Account with a balance that uses many decimal places.
  Act: Call the Output method with this account.
  Assert: Verify that the Balance in the output maintains the precision without unexpected rounding.
Validation:
  This test checks the precision handling of the Balance field, ensuring that no data is lost in the conversion process, which is crucial for financial applications.

Scenario 4: RFC3339 Time Format

Details:
  Description: Ensure that the CreatedAt field is correctly formatted as per RFC3339.
Execution:
  Arrange: Create a domain.Account with a known creation time.
  Act: Call the Output method with this account.
  Assert: Check that the CreatedAt string in the output matches the RFC3339 format.
Validation:
  Proper time formatting is essential for consistency and interoperability, especially when the data might be used across different systems or time zones.

Scenario 5: Long String Handling

Details:
  Description: Test the handling of accounts with exceptionally long string fields (Name and CPF).
Execution:
  Arrange: Create a domain.Account with very long strings for Name and CPF.
  Act: Call the Output method with this account.
  Assert: Verify that the long strings are preserved exactly in the output.
Validation:
  This test ensures that the method doesn't truncate or modify long input strings, which could be important for maintaining data integrity for unusual but valid inputs.

Scenario 6: Special Characters in Strings

Details:
  Description: Verify correct handling of special characters and Unicode in Name and CPF fields.
Execution:
  Arrange: Create a domain.Account with Name and CPF containing special characters and Unicode.
  Act: Call the Output method with this account.
  Assert: Check that the special characters are preserved correctly in the output.
Validation:
  This test is important for ensuring the application can handle diverse inputs correctly, which is crucial for internationalization and avoiding data corruption.

Scenario 7: UUID to String Conversion

Details:
  Description: Test that the account ID is correctly converted from UUID to string.
Execution:
  Arrange: Create a domain.Account with a known UUID.
  Act: Call the Output method with this account.
  Assert: Verify that the ID in the output is the correct string representation of the UUID.
Validation:
  Proper ID conversion is critical for maintaining traceability and consistency across different parts of the system that may handle IDs differently.
```

These scenarios cover a range of normal operations and potential edge cases for the `Output` method. They focus on data integrity, precision, formatting, and handling of various input types, which are all important aspects of a financial application's data processing.
*/

// ********RoostGPT********
package presenter

import (
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"

	"github.com/gsabadini/go-clean-architecture/domain"
	"github.com/gsabadini/go-clean-architecture/usecase"
)

func TestcreateAccountPresenterOutput(t *testing.T) {
	tests := []struct {
		name     string
		input    domain.Account
		expected usecase.CreateAccountOutput
	}{
		{
			name: "Valid Account Conversion",
			input: createTestAccount(
				domain.AccountID(uuid.MustParse("550e8400-e29b-41d4-a716-446655440000").String()),
				"John Doe",
				"123.456.789-00",
				domain.Money(100050), // 1000.50 * 100
				time.Date(2023, 5, 15, 10, 30, 0, 0, time.UTC),
			),
			expected: usecase.CreateAccountOutput{
				ID:        "550e8400-e29b-41d4-a716-446655440000",
				Name:      "John Doe",
				CPF:       "123.456.789-00",
				Balance:   1000.50,
				CreatedAt: "2023-05-15T10:30:00Z",
			},
		},
		{
			name: "Zero Balance Account",
			input: createTestAccount(
				domain.AccountID(uuid.MustParse("550e8400-e29b-41d4-a716-446655440001").String()),
				"Jane Smith",
				"987.654.321-00",
				domain.Money(0),
				time.Date(2023, 5, 16, 14, 45, 0, 0, time.UTC),
			),
			expected: usecase.CreateAccountOutput{
				ID:        "550e8400-e29b-41d4-a716-446655440001",
				Name:      "Jane Smith",
				CPF:       "987.654.321-00",
				Balance:   0.0,
				CreatedAt: "2023-05-16T14:45:00Z",
			},
		},
		{
			name: "Maximum Precision Balance",
			input: createTestAccount(
				domain.AccountID(uuid.MustParse("550e8400-e29b-41d4-a716-446655440002").String()),
				"Alice Johnson",
				"111.222.333-44",
				domain.Money(123456789012), // 1234.56789012 * 100
				time.Date(2023, 5, 17, 9, 0, 0, 0, time.UTC),
			),
			expected: usecase.CreateAccountOutput{
				ID:        "550e8400-e29b-41d4-a716-446655440002",
				Name:      "Alice Johnson",
				CPF:       "111.222.333-44",
				Balance:   1234.56789012,
				CreatedAt: "2023-05-17T09:00:00Z",
			},
		},
		{
			name: "Long String Handling",
			input: createTestAccount(
				domain.AccountID(uuid.MustParse("550e8400-e29b-41d4-a716-446655440003").String()),
				"This is a very long name that exceeds the usual length of names to test string handling",
				"000.111.222-33-This-Is-A-Very-Long-CPF",
				domain.Money(50000), // 500 * 100
				time.Date(2023, 5, 18, 12, 30, 0, 0, time.UTC),
			),
			expected: usecase.CreateAccountOutput{
				ID:        "550e8400-e29b-41d4-a716-446655440003",
				Name:      "This is a very long name that exceeds the usual length of names to test string handling",
				CPF:       "000.111.222-33-This-Is-A-Very-Long-CPF",
				Balance:   500,
				CreatedAt: "2023-05-18T12:30:00Z",
			},
		},
		{
			name: "Special Characters in Strings",
			input: createTestAccount(
				domain.AccountID(uuid.MustParse("550e8400-e29b-41d4-a716-446655440004").String()),
				"Spécial Nãme with Ùnicode",
				"123.456.789-00-!@#$%^&*()",
				domain.Money(75025), // 750.25 * 100
				time.Date(2023, 5, 19, 16, 15, 0, 0, time.UTC),
			),
			expected: usecase.CreateAccountOutput{
				ID:        "550e8400-e29b-41d4-a716-446655440004",
				Name:      "Spécial Nãme with Ùnicode",
				CPF:       "123.456.789-00-!@#$%^&*()",
				Balance:   750.25,
				CreatedAt: "2023-05-19T16:15:00Z",
			},
		},
	}

	presenter := createAccountPresenter{}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := presenter.Output(tt.input)
			assert.Equal(t, tt.expected, result)
		})
	}
}

// Helper function to create a domain.Account for testing
func createTestAccount(id domain.AccountID, name, cpf string, balance domain.Money, createdAt time.Time) domain.Account {
	account := domain.Account{}
	account.ID = func() domain.AccountID { return id }
	account.Name = func() string { return name }
	account.CPF = func() string { return cpf }
	account.Balance = func() domain.Money { return balance }
	account.CreatedAt = func() time.Time { return createdAt }
	return account
}
