// ********RoostGPT********
/*
Test generated by RoostGPT for test mayankzbio-go-clean using AI Type Claude AI and AI Model claude-3-5-sonnet-20240620

ROOST_METHOD_HASH=Output_7bcd1fa1d0
ROOST_METHOD_SIG_HASH=Output_1f9cab4653

FUNCTION_DEF=func (a findAllAccountPresenter) Output(accounts []domain.Account) []usecase.FindAllAccountOutput
Based on the provided function and context, I'll generate several test scenarios for the `Output` method of the `findAllAccountPresenter` struct. Here are the test scenarios:

```
Scenario 1: Empty Account List

Details:
  Description: Test the behavior of the Output method when given an empty list of accounts.
Execution:
  Arrange: Create an empty slice of domain.Account.
  Act: Call the Output method with the empty slice.
  Assert: Verify that the returned slice of usecase.FindAllAccountOutput is also empty.
Validation:
  This test ensures that the function correctly handles empty input, returning an empty output slice without errors. It's important to validate edge cases like empty inputs to prevent potential nil pointer dereferences or unexpected behavior in the application.

Scenario 2: Single Account Conversion

Details:
  Description: Test the conversion of a single domain.Account to usecase.FindAllAccountOutput.
Execution:
  Arrange: Create a slice with one domain.Account, populating all fields with known values.
  Act: Call the Output method with the single-item slice.
  Assert: Verify that the returned slice contains exactly one usecase.FindAllAccountOutput item with correctly converted values.
Validation:
  This test confirms that the function accurately converts domain.Account fields to usecase.FindAllAccountOutput fields, including proper formatting of ID, balance, and creation time. It's crucial to ensure data integrity and correct representation in the use case layer.

Scenario 3: Multiple Accounts Conversion

Details:
  Description: Test the conversion of multiple domain.Account objects to usecase.FindAllAccountOutput objects.
Execution:
  Arrange: Create a slice with multiple domain.Account objects, each with unique values.
  Act: Call the Output method with the multi-item slice.
  Assert: Verify that the returned slice contains the correct number of usecase.FindAllAccountOutput items, each with accurately converted values.
Validation:
  This test ensures that the function correctly handles multiple accounts, maintaining order and accurately converting each account. It's important to verify that the function scales properly with varying input sizes.

Scenario 4: Account with Zero Balance

Details:
  Description: Test the conversion of an account with a zero balance to ensure proper handling of this edge case.
Execution:
  Arrange: Create a domain.Account with a balance of zero.
  Act: Call the Output method with a slice containing this account.
  Assert: Verify that the returned usecase.FindAllAccountOutput correctly represents the zero balance as 0.0.
Validation:
  This test checks the handling of zero values, which can sometimes cause issues in floating-point representations. It's important to ensure that zero balances are correctly represented in the output.

Scenario 5: Account with Very Large Balance

Details:
  Description: Test the conversion of an account with a very large balance to check for any potential overflow or precision issues.
Execution:
  Arrange: Create a domain.Account with a very large balance (e.g., close to max float64 value).
  Act: Call the Output method with a slice containing this account.
  Assert: Verify that the returned usecase.FindAllAccountOutput correctly represents the large balance without loss of precision.
Validation:
  This test ensures that the function handles extreme values correctly, maintaining precision and avoiding overflow errors. It's crucial for financial applications to handle large monetary values accurately.

Scenario 6: Account with Special Characters in Name and CPF

Details:
  Description: Test the conversion of an account with special characters in the name and CPF fields to ensure proper handling.
Execution:
  Arrange: Create a domain.Account with special characters (e.g., accents, symbols) in the name and CPF fields.
  Act: Call the Output method with a slice containing this account.
  Assert: Verify that the returned usecase.FindAllAccountOutput correctly preserves the special characters in the name and CPF fields.
Validation:
  This test checks the function's ability to handle non-standard input correctly, ensuring that special characters are not lost or corrupted during the conversion process. This is important for maintaining data integrity and supporting diverse user inputs.
```

These test scenarios cover various aspects of the `Output` method, including normal operation, edge cases, and potential error conditions. They aim to ensure the correct functionality of the method across different input types and sizes.
*/

// ********RoostGPT********
package presenter

import (
	"reflect"
	"testing"
	"time"

	"github.com/gsabadini/go-clean-architecture/domain"
	"github.com/gsabadini/go-clean-architecture/usecase"
)

func TestfindAllAccountPresenterOutput(t *testing.T) {
	tests := []struct {
		name     string
		accounts []domain.Account
		want     []usecase.FindAllAccountOutput
	}{
		{
			name:     "Empty Account List",
			accounts: []domain.Account{},
			want:     []usecase.FindAllAccountOutput{},
		},
		{
			name: "Single Account Conversion",
			accounts: []domain.Account{
				createTestAccount("acc123", "John Doe", "123.456.789-00", 100.50, time.Date(2023, 5, 1, 10, 0, 0, 0, time.UTC)),
			},
			want: []usecase.FindAllAccountOutput{
				{
					ID:        "acc123",
					Name:      "John Doe",
					CPF:       "123.456.789-00",
					Balance:   100.50,
					CreatedAt: "2023-05-01T10:00:00Z",
				},
			},
		},
		{
			name: "Multiple Accounts Conversion",
			accounts: []domain.Account{
				createTestAccount("acc123", "John Doe", "123.456.789-00", 100.50, time.Date(2023, 5, 1, 10, 0, 0, 0, time.UTC)),
				createTestAccount("acc456", "Jane Smith", "987.654.321-00", 200.75, time.Date(2023, 5, 2, 11, 0, 0, 0, time.UTC)),
			},
			want: []usecase.FindAllAccountOutput{
				{
					ID:        "acc123",
					Name:      "John Doe",
					CPF:       "123.456.789-00",
					Balance:   100.50,
					CreatedAt: "2023-05-01T10:00:00Z",
				},
				{
					ID:        "acc456",
					Name:      "Jane Smith",
					CPF:       "987.654.321-00",
					Balance:   200.75,
					CreatedAt: "2023-05-02T11:00:00Z",
				},
			},
		},
		{
			name: "Account with Zero Balance",
			accounts: []domain.Account{
				createTestAccount("acc789", "Zero Balance", "111.222.333-44", 0, time.Date(2023, 5, 3, 12, 0, 0, 0, time.UTC)),
			},
			want: []usecase.FindAllAccountOutput{
				{
					ID:        "acc789",
					Name:      "Zero Balance",
					CPF:       "111.222.333-44",
					Balance:   0,
					CreatedAt: "2023-05-03T12:00:00Z",
				},
			},
		},
		{
			name: "Account with Very Large Balance",
			accounts: []domain.Account{
				createTestAccount("acc999", "Large Balance", "555.666.777-88", 1e15, time.Date(2023, 5, 4, 13, 0, 0, 0, time.UTC)),
			},
			want: []usecase.FindAllAccountOutput{
				{
					ID:        "acc999",
					Name:      "Large Balance",
					CPF:       "555.666.777-88",
					Balance:   1e15,
					CreatedAt: "2023-05-04T13:00:00Z",
				},
			},
		},
		{
			name: "Account with Special Characters",
			accounts: []domain.Account{
				createTestAccount("accSpecial", "João da Silva", "999.888.777-66", 150.25, time.Date(2023, 5, 5, 14, 0, 0, 0, time.UTC)),
			},
			want: []usecase.FindAllAccountOutput{
				{
					ID:        "accSpecial",
					Name:      "João da Silva",
					CPF:       "999.888.777-66",
					Balance:   150.25,
					CreatedAt: "2023-05-05T14:00:00Z",
				},
			},
		},
	}

	presenter := findAllAccountPresenter{}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := presenter.Output(tt.accounts)
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("findAllAccountPresenter.Output() = %v, want %v", got, tt.want)
			}
		})
	}
}

// Helper function to create a test account
func createTestAccount(id, name, cpf string, balance float64, createdAt time.Time) domain.Account {
	return domain.Account{
		ID:        domain.AccountID(id),
		Name:      name,
		CPF:       cpf,
		Balance:   domain.Money(balance * 100), // Convert to cents
		CreatedAt: createdAt,
	}
}
