// ********RoostGPT********
/*
Test generated by RoostGPT for test mayankzbio-go-clean using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=findAllAccountPresenter_Output_6a8d5877b9
ROOST_METHOD_SIG_HASH=findAllAccountPresenter_Output_1f9cab4653

FUNCTION_DEF=func (a findAllAccountPresenter) Output(accounts []domain.Account) []usecase.FindAllAccountOutput
Existing Test Information:
These test cases are already implemented and not included for test generation scenario:
File: go-clean-architecture/adapter/presenter/create_account_test.go
Test Cases:
    [Test_createAccountPresenter_Output]

File: go-clean-architecture/adapter/presenter/create_transfer_test.go
Test Cases:
    [Test_createTransferPresenter_Output]

File: go-clean-architecture/adapter/presenter/find_account_balance_test.go
Test Cases:
    [Test_findAccountBalancePresenter_Output]

File: go-clean-architecture/adapter/presenter/find_all_account_test.go
Test Cases:
    [Test_findAllAccountPresenter_Output]

File: go-clean-architecture/adapter/presenter/find_all_transfer_test.go
Test Cases:
    [Test_findAllTransferPresenter_Output]

```
Scenario 1: Convert a Single Account to Output Format

Details:
  Description: This test checks the function's ability to convert a single `domain.Account` into the `usecase.FindAllAccountOutput` format.
Execution:
  Arrange: Create a single `domain.Account` with specific ID, name, CPF, balance, and creation date.
  Act: Call the `Output` method with the single account.
  Assert: Verify that the returned slice contains exactly one `FindAllAccountOutput` with the expected values.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion ensures that the function correctly maps each field from the `domain.Account` to the `FindAllAccountOutput` structure.
  Discuss the importance of the test in relation to the application's behavior or business requirements: This test ensures that the function can handle the basic use case of converting a single account, which is fundamental to its operation.

Scenario 2: Convert Multiple Accounts to Output Format

Details:
  Description: This test verifies the function's ability to handle and convert multiple `domain.Account` instances into the `usecase.FindAllAccountOutput` format.
Execution:
  Arrange: Create a list of multiple `domain.Account` instances with varying data.
  Act: Call the `Output` method with the list of accounts.
  Assert: Check that the returned slice contains `FindAllAccountOutput` entries corresponding to each input account, with correctly mapped fields.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion ensures that each account is independently and correctly converted, maintaining data integrity across multiple entries.
  Discuss the importance of the test in relation to the application's behavior or business requirements: This test is crucial for ensuring that the function can handle typical use cases involving multiple accounts, which is common in real-world applications.

Scenario 3: Handle Empty Account List

Details:
  Description: This test checks the function's behavior when provided with an empty list of accounts.
Execution:
  Arrange: Prepare an empty slice of `domain.Account`.
  Act: Call the `Output` method with the empty slice.
  Assert: Verify that the returned slice is also empty.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion confirms that the function correctly handles edge cases without errors or unexpected behavior.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Handling empty inputs gracefully is important for robustness and preventing runtime errors in edge cases.

Scenario 4: Handle Accounts with Zero Balance

Details:
  Description: This test examines the function's ability to correctly convert accounts with a zero balance.
Execution:
  Arrange: Create a `domain.Account` with a balance of zero.
  Act: Call the `Output` method with the account.
  Assert: Ensure that the `Balance` field in the output is correctly set to 0.0.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion checks that the conversion logic correctly interprets and formats zero balances.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Correctly handling zero balances is important for financial applications to ensure accurate reporting and calculations.

Scenario 5: Handle Accounts with Large Balances

Details:
  Description: This test verifies the function's ability to handle accounts with large balance values.
Execution:
  Arrange: Create a `domain.Account` with a very large balance.
  Act: Call the `Output` method with the account.
  Assert: Confirm that the `Balance` field in the output accurately reflects the large balance.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion ensures that the function can handle large numerical values without overflow or precision loss.
  Discuss the importance of the test in relation to the application's behavior or business requirements: This test is important for applications dealing with financial data, where large balances are common and must be accurately represented.

Scenario 6: Handle Accounts with Special Characters in Name

Details:
  Description: This test checks the function's ability to handle account names containing special characters.
Execution:
  Arrange: Create a `domain.Account` with a name that includes special characters.
  Act: Call the `Output` method with the account.
  Assert: Verify that the `Name` field in the output correctly includes the special characters.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion confirms that the function does not alter or strip special characters from account names.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Handling special characters correctly is important for maintaining data integrity, especially in international applications where names may include a variety of characters.
```
*/

// ********RoostGPT********
package presenter

import (
	"reflect"
	"testing"
	"time"

	"github.com/gsabadini/go-clean-architecture/domain"
	"github.com/gsabadini/go-clean-architecture/usecase"
)

type findAllAccountPresenter struct{}

func (a findAllAccountPresenter) Output(accounts []domain.Account) []usecase.FindAllAccountOutput {
	var o = make([]usecase.FindAllAccountOutput, 0)
	for _, account := range accounts {
		o = append(o, usecase.FindAllAccountOutput{
			ID:        account.ID().String(),
			Name:      account.Name(),
			CPF:       account.CPF(),
			Balance:   account.Balance().Float64(),
			CreatedAt: account.CreatedAt().Format(time.RFC3339),
		})
	}
	return o
}

func Test_findAllAccountPresenter_Output(t *testing.T) {
	type args struct {
		accounts []domain.Account
	}
	tests := []struct {
		name string
		args args
		want []usecase.FindAllAccountOutput
	}{
		{
			name: "Convert a Single Account to Output Format",
			args: args{
				accounts: []domain.Account{
					domain.NewAccount("3c096a40-ccba-4b58-93ed-57379ab04680", "SingleAccount", "07091054965", 1000, time.Time{}),
				},
			},
			want: []usecase.FindAllAccountOutput{
				{
					ID:        "3c096a40-ccba-4b58-93ed-57379ab04680",
					Name:      "SingleAccount",
					CPF:       "07091054965",
					Balance:   10.0,
					CreatedAt: "0001-01-01T00:00:00Z",
				},
			},
		},
		{
			name: "Convert Multiple Accounts to Output Format",
			args: args{
				accounts: []domain.Account{
					domain.NewAccount("3c096a40-ccba-4b58-93ed-57379ab04680", "Account1", "07091054965", 1000, time.Time{}),
					domain.NewAccount("3c096a40-ccba-4b58-93ed-57379ab04681", "Account2", "07091054966", 2000, time.Time{}),
				},
			},
			want: []usecase.FindAllAccountOutput{
				{
					ID:        "3c096a40-ccba-4b58-93ed-57379ab04680",
					Name:      "Account1",
					CPF:       "07091054965",
					Balance:   10.0,
					CreatedAt: "0001-01-01T00:00:00Z",
				},
				{
					ID:        "3c096a40-ccba-4b58-93ed-57379ab04681",
					Name:      "Account2",
					CPF:       "07091054966",
					Balance:   20.0,
					CreatedAt: "0001-01-01T00:00:00Z",
				},
			},
		},
		{
			name: "Handle Empty Account List",
			args: args{
				accounts: []domain.Account{},
			},
			want: []usecase.FindAllAccountOutput{},
		},
		{
			name: "Handle Accounts with Zero Balance",
			args: args{
				accounts: []domain.Account{
					domain.NewAccount("3c096a40-ccba-4b58-93ed-57379ab04680", "ZeroBalance", "07091054965", 0, time.Time{}),
				},
			},
			want: []usecase.FindAllAccountOutput{
				{
					ID:        "3c096a40-ccba-4b58-93ed-57379ab04680",
					Name:      "ZeroBalance",
					CPF:       "07091054965",
					Balance:   0.0,
					CreatedAt: "0001-01-01T00:00:00Z",
				},
			},
		},
		{
			name: "Handle Accounts with Large Balances",
			args: args{
				accounts: []domain.Account{
					domain.NewAccount("3c096a40-ccba-4b58-93ed-57379ab04680", "LargeBalance", "07091054965", 1000000000, time.Time{}),
				},
			},
			want: []usecase.FindAllAccountOutput{
				{
					ID:        "3c096a40-ccba-4b58-93ed-57379ab04680",
					Name:      "LargeBalance",
					CPF:       "07091054965",
					Balance:   10000000.0,
					CreatedAt: "0001-01-01T00:00:00Z",
				},
			},
		},
		{
			name: "Handle Accounts with Special Characters in Name",
			args: args{
				accounts: []domain.Account{
					domain.NewAccount("3c096a40-ccba-4b58-93ed-57379ab04680", "Special!@#$%^&*()_+", "07091054965", 1000, time.Time{}),
				},
			},
			want: []usecase.FindAllAccountOutput{
				{
					ID:        "3c096a40-ccba-4b58-93ed-57379ab04680",
					Name:      "Special!@#$%^&*()_+",
					CPF:       "07091054965",
					Balance:   10.0,
					CreatedAt: "0001-01-01T00:00:00Z",
				},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			pre := findAllAccountPresenter{}
			if got := pre.Output(tt.args.accounts); !reflect.DeepEqual(got, tt.want) {
				t.Errorf("[TestCase '%s'] Got: '%+v' | Want: '%+v'", tt.name, got, tt.want)
			}
		})
	}
}
