// ********RoostGPT********
/*
Test generated by RoostGPT for test mayankzbio-go-clean using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=NewError_60f21bdfe6
ROOST_METHOD_SIG_HASH=NewError_2777a10962

FUNCTION_DEF=func NewError(log logger.Logger, err error, key string, httpStatus int) Error
```
Scenario 1: Creating an Error with Valid Inputs

Details:
  Description: This test checks if the `NewError` function correctly initializes an `Error` struct when provided with valid inputs, including a logger, an error, a key, and an HTTP status code.
Execution:
  Arrange: Create a mock or stub for the `logger.Logger` interface, define a sample error, a key string, and an HTTP status code.
  Act: Call `NewError` with the arranged inputs.
  Assert: Verify that the returned `Error` struct contains the expected values for each field.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The test ensures that the function correctly assigns the provided inputs to the respective fields of the `Error` struct.
  Discuss the importance of the test in relation to the application's behavior or business requirements: This test confirms that the function behaves as expected under normal conditions, which is crucial for error handling and logging in the application.

Scenario 2: Handling a Nil Logger

Details:
  Description: This test checks how the `NewError` function behaves when a nil logger is provided, ensuring that the function can handle this edge case without causing a panic.
Execution:
  Arrange: Set the logger to nil, define a sample error, a key string, and an HTTP status code.
  Act: Call `NewError` with the arranged inputs.
  Assert: Verify that the returned `Error` struct has a nil logger field and the other fields are correctly assigned.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The test ensures that the function can handle a nil logger gracefully, which is important for robustness.
  Discuss the importance of the test in relation to the application's behavior or business requirements: This test ensures that the application can continue to function even if the logger is not available, which is crucial for maintaining stability.

Scenario 3: Handling a Nil Error

Details:
  Description: This test checks how the `NewError` function behaves when a nil error is provided, ensuring that the function can handle this edge case without causing a panic.
Execution:
  Arrange: Create a mock or stub for the `logger.Logger` interface, set the error to nil, define a key string, and an HTTP status code.
  Act: Call `NewError` with the arranged inputs.
  Assert: Verify that the returned `Error` struct has a nil error field and the other fields are correctly assigned.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The test ensures that the function can handle a nil error gracefully, which is important for robustness.
  Discuss the importance of the test in relation to the application's behavior or business requirements: This test ensures that the application can continue to function even if an error is not provided, which is crucial for maintaining stability.

Scenario 4: Handling an Empty Key

Details:
  Description: This test checks how the `NewError` function behaves when an empty key string is provided, ensuring that the function can handle this edge case.
Execution:
  Arrange: Create a mock or stub for the `logger.Logger` interface, define a sample error, set the key to an empty string, and an HTTP status code.
  Act: Call `NewError` with the arranged inputs.
  Assert: Verify that the returned `Error` struct has an empty key field and the other fields are correctly assigned.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The test ensures that the function can handle an empty key string, which might be valid in some contexts.
  Discuss the importance of the test in relation to the application's behavior or business requirements: This test ensures that the function can handle cases where a key might not be provided, which is important for flexibility.

Scenario 5: Handling a Zero HTTP Status Code

Details:
  Description: This test checks how the `NewError` function behaves when a zero HTTP status code is provided, ensuring that the function can handle this edge case.
Execution:
  Arrange: Create a mock or stub for the `logger.Logger` interface, define a sample error, a key string, and set the HTTP status code to zero.
  Act: Call `NewError` with the arranged inputs.
  Assert: Verify that the returned `Error` struct has a zero HTTP status code field and the other fields are correctly assigned.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The test ensures that the function can handle a zero HTTP status code, which might be valid in some contexts.
  Discuss the importance of the test in relation to the application's behavior or business requirements: This test ensures that the function can handle cases where an HTTP status code might not be provided, which is important for flexibility.
```
*/

// ********RoostGPT********
package logging

import (
	"errors"
	"testing"

	"github.com/gsabadini/go-clean-architecture/adapter/logger"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

// MockLogger is a mock implementation of the logger.Logger interface
type MockLogger struct {
	mock.Mock
}

func (m *MockLogger) Infof(format string, args ...interface{}) {
	m.Called(format, args)
}

func (m *MockLogger) Warnf(format string, args ...interface{}) {
	m.Called(format, args)
}

func (m *MockLogger) Errorf(format string, args ...interface{}) {
	m.Called(format, args)
}

func (m *MockLogger) Fatalln(args ...interface{}) {
	m.Called(args)
}

func (m *MockLogger) WithFields(keyValues logger.Fields) logger.Logger {
	args := m.Called(keyValues)
	return args.Get(0).(logger.Logger)
}

func (m *MockLogger) WithError(err error) logger.Logger {
	args := m.Called(err)
	return args.Get(0).(logger.Logger)
}

type Fields map[string]interface{}

type Error struct {
	log        logger.Logger
	err        error
	key        string
	httpStatus int
}

func NewError(log logger.Logger, err error, key string, httpStatus int) Error {
	return Error{log: log, err: err, key: key, httpStatus: httpStatus}
}

func TestNewError(t *testing.T) {
	tests := []struct {
		name       string
		log        logger.Logger
		err        error
		key        string
		httpStatus int
		expected   Error
	}{
		{
			name:       "Creating an Error with Valid Inputs",
			log:        &MockLogger{},
			err:        errors.New("sample error"),
			key:        "sampleKey",
			httpStatus: 200,
			expected:   Error{log: &MockLogger{}, err: errors.New("sample error"), key: "sampleKey", httpStatus: 200},
		},
		{
			name:       "Handling a Nil Logger",
			log:        nil,
			err:        errors.New("sample error"),
			key:        "sampleKey",
			httpStatus: 200,
			expected:   Error{log: nil, err: errors.New("sample error"), key: "sampleKey", httpStatus: 200},
		},
		{
			name:       "Handling a Nil Error",
			log:        &MockLogger{},
			err:        nil,
			key:        "sampleKey",
			httpStatus: 200,
			expected:   Error{log: &MockLogger{}, err: nil, key: "sampleKey", httpStatus: 200},
		},
		{
			name:       "Handling an Empty Key",
			log:        &MockLogger{},
			err:        errors.New("sample error"),
			key:        "",
			httpStatus: 200,
			expected:   Error{log: &MockLogger{}, err: errors.New("sample error"), key: "", httpStatus: 200},
		},
		{
			name:       "Handling a Zero HTTP Status Code",
			log:        &MockLogger{},
			err:        errors.New("sample error"),
			key:        "sampleKey",
			httpStatus: 0,
			expected:   Error{log: &MockLogger{}, err: errors.New("sample error"), key: "sampleKey", httpStatus: 0},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := NewError(tt.log, tt.err, tt.key, tt.httpStatus)
			assert.Equal(t, tt.expected.log, result.log)
			assert.Equal(t, tt.expected.err, result.err)
			assert.Equal(t, tt.expected.key, result.key)
			assert.Equal(t, tt.expected.httpStatus, result.httpStatus)
			t.Logf("Test %s passed", tt.name)
		})
	}
}
