// ********RoostGPT********
/*
Test generated by RoostGPT for test mayankzbio-go-clean using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=Info_Log_ffb442bc76
ROOST_METHOD_SIG_HASH=Info_Log_6ef6a22ae0

FUNCTION_DEF=func (i Info) Log(msg string)
```
Scenario 1: Log Message with Valid Key and HTTP Status

Details:
  Description: This test checks that the `Log` function correctly logs a message with valid `key` and `httpStatus` fields.
Execution:
  Arrange: Create a mock logger that implements the `logger.Logger` interface. Initialize an `Info` struct with the mock logger, a valid `key`, and a valid `httpStatus`.
  Act: Call the `Log` method on the `Info` struct with a sample message.
  Assert: Verify that the mock logger's `Infof` method is called with the expected message and that the `WithFields` method is called with the correct fields.
Validation:
  The assertion ensures that the `Log` function correctly formats and logs the message with the provided fields. This test is important to confirm that the logging mechanism captures and logs the necessary context for debugging and monitoring.

Scenario 2: Log Message with Empty Key

Details:
  Description: This test checks the behavior of the `Log` function when the `key` field is empty.
Execution:
  Arrange: Create a mock logger and initialize an `Info` struct with the mock logger, an empty `key`, and a valid `httpStatus`.
  Act: Call the `Log` method with a sample message.
  Assert: Verify that the `Infof` method is called and that the `WithFields` method includes an empty `key` field.
Validation:
  The test ensures that the logging function handles empty `key` values gracefully without causing errors. This is important for robustness, as it verifies that the system can handle incomplete data without failing.

Scenario 3: Log Message with Zero HTTP Status

Details:
  Description: This test examines the behavior of the `Log` function when the `httpStatus` is set to zero.
Execution:
  Arrange: Create a mock logger and initialize an `Info` struct with the mock logger, a valid `key`, and an `httpStatus` of zero.
  Act: Call the `Log` method with a sample message.
  Assert: Verify that the `Infof` method is called and that the `WithFields` method includes an `httpStatus` field set to zero.
Validation:
  This test checks that the function can handle a zero `httpStatus` without errors, which is crucial for scenarios where the status might not be set or is intentionally zero.

Scenario 4: Log Message with Special Characters in Key

Details:
  Description: This test checks how the `Log` function handles a `key` containing special characters.
Execution:
  Arrange: Create a mock logger and initialize an `Info` struct with the mock logger, a `key` containing special characters, and a valid `httpStatus`.
  Act: Call the `Log` method with a sample message.
  Assert: Verify that the `Infof` method is called and that the `WithFields` method includes the `key` with special characters.
Validation:
  The test ensures that special characters in the `key` do not cause logging errors, which is important for supporting a wide range of input data.

Scenario 5: Log Message with Long Message String

Details:
  Description: This test evaluates the `Log` function's ability to handle a very long message string.
Execution:
  Arrange: Create a mock logger and initialize an `Info` struct with the mock logger, a valid `key`, and `httpStatus`. Prepare a long message string.
  Act: Call the `Log` method with the long message string.
  Assert: Verify that the `Infof` method is called with the long message and that the `WithFields` method is called with the correct fields.
Validation:
  This test checks the function's performance and stability when handling large input sizes, ensuring that the logging system can manage extensive data without crashing or truncating important information.
```
*/

// ********RoostGPT********
package logging

import (
	"testing"

	"github.com/gsabadini/go-clean-architecture/adapter/logger"
	"github.com/stretchr/testify/mock"
)

// MockLogger is a mock implementation of the logger.Logger interface
type MockLogger struct {
	mock.Mock
}

func (m *MockLogger) Infof(format string, args ...interface{}) {
	m.Called(format, args)
}

func (m *MockLogger) Warnf(format string, args ...interface{}) {
	m.Called(format, args)
}

func (m *MockLogger) Errorf(format string, args ...interface{}) {
	m.Called(format, args)
}

func (m *MockLogger) Fatalln(args ...interface{}) {
	m.Called(args)
}

func (m *MockLogger) WithFields(keyValues logger.Fields) logger.Logger {
	args := m.Called(keyValues)
	return args.Get(0).(logger.Logger)
}

func (m *MockLogger) WithError(err error) logger.Logger {
	args := m.Called(err)
	return args.Get(0).(logger.Logger)
}

type Info struct {
	log        logger.Logger
	key        string
	httpStatus int
}

func (i Info) Log(msg string) {
	i.log.WithFields(logger.Fields{"key": i.key, "http_status": i.httpStatus}).Infof(msg)
}

func TestInfoInfoLog(t *testing.T) {
	tests := []struct {
		name       string
		key        string
		httpStatus int
		message    string
	}{
		{
			name:       "Log Message with Valid Key and HTTP Status",
			key:        "validKey",
			httpStatus: 200,
			message:    "Sample message",
		},
		{
			name:       "Log Message with Empty Key",
			key:        "",
			httpStatus: 200,
			message:    "Sample message",
		},
		{
			name:       "Log Message with Zero HTTP Status",
			key:        "validKey",
			httpStatus: 0,
			message:    "Sample message",
		},
		{
			name:       "Log Message with Special Characters in Key",
			key:        "special!@#$%^&*()",
			httpStatus: 200,
			message:    "Sample message",
		},
		{
			name:       "Log Message with Long Message String",
			key:        "validKey",
			httpStatus: 200,
			message:    "This is a very long message string to test the logging functionality and ensure that it handles large input sizes without crashing or truncating important information.",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			mockLogger := new(MockLogger)
			info := Info{
				log:        mockLogger,
				key:        tt.key,
				httpStatus: tt.httpStatus,
			}

			mockLogger.On("WithFields", logger.Fields{"key": tt.key, "http_status": tt.httpStatus}).Return(mockLogger)
			mockLogger.On("Infof", tt.message, mock.Anything).Return()

			info.Log(tt.message)

			mockLogger.AssertCalled(t, "WithFields", logger.Fields{"key": tt.key, "http_status": tt.httpStatus})
			mockLogger.AssertCalled(t, "Infof", tt.message, mock.Anything)
		})
	}
}
