// ********RoostGPT********
/*
Test generated by RoostGPT for test mayankzbio-go-clean using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=Error_Log_fb2f1c1ea1
ROOST_METHOD_SIG_HASH=Error_Log_8d7b4769e9

FUNCTION_DEF=func (e Error) Log(msg string)
```
Scenario 1: Log an Error with Valid Fields

Details:
  Description: This test checks if the `Log` function correctly logs an error message with the expected fields when provided with valid inputs.
Execution:
  Arrange: Create a mock logger that implements the `logger.Logger` interface. Instantiate an `Error` struct with a valid error, key, and HTTP status.
  Act: Call the `Log` method on the `Error` instance with a sample message.
  Assert: Verify that the mock logger's `Errorf` method is called with the correct message and fields.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion ensures that the `Errorf` method is invoked with the correct parameters, confirming that the error logging functionality works as intended.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Proper logging is crucial for debugging and monitoring application behavior, making this test essential for maintaining reliable error tracking.

Scenario 2: Log an Error with Nil Error Field

Details:
  Description: This test checks the behavior of the `Log` function when the `Error` struct contains a nil error field.
Execution:
  Arrange: Create a mock logger and instantiate an `Error` struct with a nil error, valid key, and HTTP status.
  Act: Call the `Log` method on the `Error` instance with a sample message.
  Assert: Verify that the mock logger's `Errorf` method is called with the correct message and fields, handling the nil error gracefully.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion ensures that the logger can handle a nil error without causing a panic or unexpected behavior.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Handling nil errors gracefully is important to prevent runtime errors and maintain application stability.

Scenario 3: Log an Error with Empty Key

Details:
  Description: This test checks the behavior of the `Log` function when the `Error` struct contains an empty key.
Execution:
  Arrange: Create a mock logger and instantiate an `Error` struct with a valid error, empty key, and HTTP status.
  Act: Call the `Log` method on the `Error` instance with a sample message.
  Assert: Verify that the mock logger's `Errorf` method is called with the correct message and fields, including the empty key.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion ensures that the logger can handle an empty key without omitting it from the log fields.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Ensuring all fields are logged, even if empty, is important for consistent log formatting and data completeness.

Scenario 4: Log an Error with Zero HTTP Status

Details:
  Description: This test checks the behavior of the `Log` function when the `Error` struct contains a zero HTTP status.
Execution:
  Arrange: Create a mock logger and instantiate an `Error` struct with a valid error, key, and zero HTTP status.
  Act: Call the `Log` method on the `Error` instance with a sample message.
  Assert: Verify that the mock logger's `Errorf` method is called with the correct message and fields, including the zero HTTP status.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion ensures that the logger includes the zero HTTP status in the log fields, verifying that all fields are logged as expected.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Logging the HTTP status, even if zero, is important for understanding the context of the error and maintaining consistency in log data.

Scenario 5: Log an Error with Special Characters in Key

Details:
  Description: This test checks the behavior of the `Log` function when the `Error` struct contains special characters in the key.
Execution:
  Arrange: Create a mock logger and instantiate an `Error` struct with a valid error, key containing special characters, and HTTP status.
  Act: Call the `Log` method on the `Error` instance with a sample message.
  Assert: Verify that the mock logger's `Errorf` method is called with the correct message and fields, including the key with special characters.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion ensures that the logger correctly handles and logs keys with special characters, maintaining data integrity.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Properly logging keys with special characters is important for ensuring that all data is accurately captured and represented in logs.
```
*/

// ********RoostGPT********

package logging

import (
	"fmt"
	"testing"

	"github.com/gsabadini/go-clean-architecture/adapter/logger"
	"github.com/stretchr/testify/mock"
)

type MockLogger struct {
	mock.Mock
}

func (m *MockLogger) Errorf(format string, args ...interface{}) {
	m.Called(format, args)
}
func (m *MockLogger) Fatalln(args ...interface{}) {
	m.Called(args)
}
func (m *MockLogger) Infof(format string, args ...interface{}) {
	m.Called(format, args)
}
func (m *MockLogger) Warnf(format string, args ...interface{}) {
	m.Called(format, args)
}
func (m *MockLogger) WithError(err error) logger.Logger {
	args := m.Called(err)
	return args.Get(0).(logger.Logger)
}
func (m *MockLogger) WithFields(keyValues logger.Fields) logger.Logger {
	args := m.Called(keyValues)
	return args.Get(0).(logger.Logger)
}
func TestErrorErrorLog(t *testing.T) {
	tests := []struct {
		name       string
		errorField error
		key        string
		httpStatus int
		message    string
	}{
		{
			name:       "Log an Error with Valid Fields",
			errorField: fmt.Errorf("sample error"),
			key:        "validKey",
			httpStatus: 500,
			message:    "An error occurred",
		},
		{
			name:       "Log an Error with Nil Error Field",
			errorField: nil,
			key:        "validKey",
			httpStatus: 500,
			message:    "An error occurred",
		},
		{
			name:       "Log an Error with Empty Key",
			errorField: fmt.Errorf("sample error"),
			key:        "",
			httpStatus: 500,
			message:    "An error occurred",
		},
		{
			name:       "Log an Error with Zero HTTP Status",
			errorField: fmt.Errorf("sample error"),
			key:        "validKey",
			httpStatus: 0,
			message:    "An error occurred",
		},
		{
			name:       "Log an Error with Special Characters in Key",
			errorField: fmt.Errorf("sample error"),
			key:        "special!@#$%^&*()",
			httpStatus: 500,
			message:    "An error occurred",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			mockLogger := new(MockLogger)
			errorInstance := Error{
				log:        mockLogger,
				err:        tt.errorField,
				key:        tt.key,
				httpStatus: tt.httpStatus,
			}

			expectedFields := logger.Fields{
				"key":         tt.key,
				"error":       "",
				"http_status": tt.httpStatus,
			}

			if tt.errorField != nil {
				expectedFields["error"] = tt.errorField.Error()
			}

			mockLogger.On("WithFields", expectedFields).Return(mockLogger)
			mockLogger.On("Errorf", tt.message).Return()

			errorInstance.Log(tt.message)

			mockLogger.AssertExpectations(t)
		})
	}
}
