// ********RoostGPT********
/*
Test generated by RoostGPT for test mayankzbio-go-clean using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=newConfigPostgres_abab268218
ROOST_METHOD_SIG_HASH=newConfigPostgres_72e851319e

FUNCTION_DEF=func newConfigPostgres() *config
```
Scenario 1: Environment Variables Set Correctly

Details:
  Description: This test checks if the `newConfigPostgres` function correctly reads and assigns values from environment variables to the config struct.
Execution:
  Arrange: Set environment variables `POSTGRES_HOST`, `POSTGRES_DATABASE`, `POSTGRES_PORT`, `POSTGRES_DRIVER`, `POSTGRES_USER`, and `POSTGRES_PASSWORD` with specific test values.
  Act: Call the `newConfigPostgres` function.
  Assert: Verify that the returned config struct contains the expected values from the environment variables.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion ensures that the function correctly reads environment variables, which is crucial for configuring database connections.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Correctly reading environment variables is essential for the application to connect to the correct database instance.

Scenario 2: Missing Environment Variables

Details:
  Description: This test checks the behavior of the `newConfigPostgres` function when some or all environment variables are not set.
Execution:
  Arrange: Ensure that none of the environment variables `POSTGRES_HOST`, `POSTGRES_DATABASE`, `POSTGRES_PORT`, `POSTGRES_DRIVER`, `POSTGRES_USER`, and `POSTGRES_PASSWORD` are set.
  Act: Call the `newConfigPostgres` function.
  Assert: Verify that the returned config struct contains empty strings for each field.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion checks for empty strings, which is the default behavior when environment variables are not set.
  Discuss the importance of the test in relation to the application's behavior or business requirements: This test ensures that the application can handle missing configuration gracefully, which is important for robustness.

Scenario 3: Partial Environment Variables Set

Details:
  Description: This test examines the function's behavior when only some of the required environment variables are set.
Execution:
  Arrange: Set only a subset of the environment variables, such as `POSTGRES_HOST` and `POSTGRES_PORT`.
  Act: Call the `newConfigPostgres` function.
  Assert: Verify that the returned config struct contains the set values for `host` and `port`, and empty strings for the unset fields.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion checks that only the set environment variables are reflected in the config struct.
  Discuss the importance of the test in relation to the application's behavior or business requirements: This test ensures partial configuration is handled correctly, which is important for debugging and development.

Scenario 4: Environment Variables with Special Characters

Details:
  Description: This test checks if the function can handle environment variables containing special characters.
Execution:
  Arrange: Set environment variables with special characters, such as `POSTGRES_PASSWORD` containing symbols.
  Act: Call the `newConfigPostgres` function.
  Assert: Verify that the returned config struct contains the exact values, including special characters.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion ensures that special characters are preserved, which is important for passwords and other sensitive data.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Handling special characters correctly is crucial for security and functionality.

Scenario 5: Environment Variables with Leading/Trailing Spaces

Details:
  Description: This test checks if the function trims leading or trailing spaces from environment variable values.
Execution:
  Arrange: Set environment variables with leading and trailing spaces.
  Act: Call the `newConfigPostgres` function.
  Assert: Verify that the returned config struct contains values without leading or trailing spaces.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion checks for trimmed values, which is important for avoiding connection errors due to malformed strings.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Ensuring clean input from environment variables helps prevent subtle bugs and connection issues.
```
*/

// ********RoostGPT********

package database

import (
	"os"
	"testing"
)

func TestNewConfigPostgres(t *testing.T) {
	type testCase struct {
		name           string
		envVars        map[string]string
		expectedConfig config
	}

	testCases := []testCase{
		{
			name: "Scenario 1: Environment Variables Set Correctly",
			envVars: map[string]string{
				"POSTGRES_HOST":     "localhost",
				"POSTGRES_DATABASE": "testdb",
				"POSTGRES_PORT":     "5432",
				"POSTGRES_DRIVER":   "postgres",
				"POSTGRES_USER":     "user",
				"POSTGRES_PASSWORD": "password",
			},
			expectedConfig: config{
				host:     "localhost",
				database: "testdb",
				port:     "5432",
				driver:   "postgres",
				user:     "user",
				password: "password",
			},
		},
		{
			name:           "Scenario 2: Missing Environment Variables",
			envVars:        map[string]string{},
			expectedConfig: config{},
		},
		{
			name: "Scenario 3: Partial Environment Variables Set",
			envVars: map[string]string{
				"POSTGRES_HOST": "localhost",
				"POSTGRES_PORT": "5432",
			},
			expectedConfig: config{
				host: "localhost",
				port: "5432",
			},
		},
		{
			name: "Scenario 4: Environment Variables with Special Characters",
			envVars: map[string]string{
				"POSTGRES_PASSWORD": "p@ssw0rd!",
			},
			expectedConfig: config{
				password: "p@ssw0rd!",
			},
		},
		{
			name: "Scenario 5: Environment Variables with Leading/Trailing Spaces",
			envVars: map[string]string{
				"POSTGRES_HOST": " localhost ",
			},
			expectedConfig: config{
				host: " localhost ",
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {

			for key, value := range tc.envVars {
				os.Setenv(key, value)
			}

			actualConfig := newConfigPostgres()

			if actualConfig.host != tc.expectedConfig.host {
				t.Errorf("Expected host: %s, got: %s", tc.expectedConfig.host, actualConfig.host)
			}
			if actualConfig.database != tc.expectedConfig.database {
				t.Errorf("Expected database: %s, got: %s", tc.expectedConfig.database, actualConfig.database)
			}
			if actualConfig.port != tc.expectedConfig.port {
				t.Errorf("Expected port: %s, got: %s", tc.expectedConfig.port, actualConfig.port)
			}
			if actualConfig.driver != tc.expectedConfig.driver {
				t.Errorf("Expected driver: %s, got: %s", tc.expectedConfig.driver, actualConfig.driver)
			}
			if actualConfig.user != tc.expectedConfig.user {
				t.Errorf("Expected user: %s, got: %s", tc.expectedConfig.user, actualConfig.user)
			}
			if actualConfig.password != tc.expectedConfig.password {
				t.Errorf("Expected password: %s, got: %s", tc.expectedConfig.password, actualConfig.password)
			}

			for key := range tc.envVars {
				os.Unsetenv(key)
			}
		})
	}
}
