// ********RoostGPT********
/*
Test generated by RoostGPT for test mayankzbio-go-clean using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=createAccountInteractor_Execute_0e0dbd7027
ROOST_METHOD_SIG_HASH=createAccountInteractor_Execute_d9b1a85a8d

FUNCTION_DEF=func (a createAccountInteractor) Execute(ctx context.Context, input CreateAccountInput) (CreateAccountOutput, error) // Execute orchestrates the use case

Existing Test Information:
These test cases are already implemented and not included for test generation scenario:
File: go-clean-architecture/usecase/create_account_test.go
Test Cases:
    [TestCreateAccountInteractor_Execute]

File: go-clean-architecture/usecase/create_transfer_test.go
Test Cases:
    [TestTransferCreateInteractor_Execute]

File: go-clean-architecture/usecase/find_account_balance_test.go
Test Cases:
    [TestFindBalanceAccountInteractor_Execute]

File: go-clean-architecture/usecase/find_all_account_test.go
Test Cases:
    [TestFindAllAccountInteractor_Execute]

File: go-clean-architecture/usecase/find_all_transfer_test.go
Test Cases:
    [TestTransferFindAllInteractor_Execute]

Here are the test scenarios for the `createAccountInteractor.Execute` function:

```
Scenario 1: Successful Account Creation with Valid Input

Details:
  Description: This test checks if the account is successfully created when provided with valid input data, ensuring that the repository and presenter interactions work as expected.
Execution:
  Arrange: Set up a mock repository that returns a valid account object and a mock presenter that formats the output correctly.
  Act: Call the `Execute` method with a valid `CreateAccountInput` containing a name, CPF, and positive balance.
  Assert: Verify that the returned `CreateAccountOutput` matches the expected output and no error is returned.
Validation:
  Explain the choice of assertion and the logic behind the expected result.
  Discuss the importance of the test in relation to the application's behavior or business requirements.

Scenario 2: Account Creation Fails Due to Repository Error

Details:
  Description: This test checks the behavior of the function when the repository returns an error during account creation, ensuring that the error is propagated correctly.
Execution:
  Arrange: Set up a mock repository that returns an error when attempting to create an account.
  Act: Call the `Execute` method with a valid `CreateAccountInput`.
  Assert: Verify that the returned error matches the expected error message and the output is empty.
Validation:
  Explain the choice of assertion and the logic behind the expected result.
  Discuss the importance of the test in relation to the application's behavior or business requirements.

Scenario 3: Account Creation with Empty Name

Details:
  Description: This test checks the function's behavior when the input name is empty, ensuring that the function handles invalid input gracefully.
Execution:
  Arrange: Set up a mock repository and presenter. Use a `CreateAccountInput` with an empty name.
  Act: Call the `Execute` method with the invalid input.
  Assert: Verify that the function returns an error indicating invalid input and the output is empty.
Validation:
  Explain the choice of assertion and the logic behind the expected result.
  Discuss the importance of the test in relation to the application's behavior or business requirements.

Scenario 4: Account Creation with Invalid CPF

Details:
  Description: This test checks the function's behavior when the input CPF is invalid, ensuring that the function validates CPF format correctly.
Execution:
  Arrange: Set up a mock repository and presenter. Use a `CreateAccountInput` with an invalid CPF.
  Act: Call the `Execute` method with the invalid input.
  Assert: Verify that the function returns an error indicating invalid CPF and the output is empty.
Validation:
  Explain the choice of assertion and the logic behind the expected result.
  Discuss the importance of the test in relation to the application's behavior or business requirements.

Scenario 5: Account Creation with Zero Balance

Details:
  Description: This test checks the function's behavior when the input balance is zero, ensuring that the function enforces the positive balance requirement.
Execution:
  Arrange: Set up a mock repository and presenter. Use a `CreateAccountInput` with a balance of zero.
  Act: Call the `Execute` method with the invalid input.
  Assert: Verify that the function returns an error indicating that the balance must be greater than zero and the output is empty.
Validation:
  Explain the choice of assertion and the logic behind the expected result.
  Discuss the importance of the test in relation to the application's behavior or business requirements.

Scenario 6: Account Creation Timeout

Details:
  Description: This test checks the function's behavior when the context times out, ensuring that the function respects the context's timeout settings.
Execution:
  Arrange: Set up a mock repository and presenter. Use a context with a very short timeout duration.
  Act: Call the `Execute` method with valid input and the short timeout context.
  Assert: Verify that the function returns a context deadline exceeded error and the output is empty.
Validation:
  Explain the choice of assertion and the logic behind the expected result.
  Discuss the importance of the test in relation to the application's behavior or business requirements.
```

These scenarios cover a range of situations, including successful operations, input validation, error handling, and context management, ensuring comprehensive testing of the `createAccountInteractor.Execute` function.
*/

// ********RoostGPT********
package usecase

import (
	"context"
	"errors"
	"reflect"
	"testing"
	"time"

	"github.com/gsabadini/go-clean-architecture/domain"
)

func TestCreateAccountInteractor_Execute(t *testing.T) {
	t.Parallel()

	type args struct {
		input CreateAccountInput
	}

	tests := []struct {
		name          string
		args          args
		repository    domain.AccountRepository
		presenter     CreateAccountPresenter
		expected      CreateAccountOutput
		expectedError interface{}
	}{
		{
			name: "Create account successful",
			args: args{
				input: CreateAccountInput{
					Name:    "Test",
					CPF:     "02815517078",
					Balance: 19944,
				},
			},
			repository: mockAccountRepoStore{
				result: domain.NewAccount("3c096a40-ccba-4b58-93ed-57379ab04680", "Test", "02815517078", 19944, time.Time{}),
				err:    nil,
			},
			presenter: mockCreateAccountPresenter{
				result: CreateAccountOutput{
					ID:        "3c096a40-ccba-4b58-93ed-57379ab04680",
					Name:      "Test",
					CPF:       "02815517078",
					Balance:   199.44,
					CreatedAt: time.Time{}.String(),
				},
			},
			expected: CreateAccountOutput{
				ID:        "3c096a40-ccba-4b58-93ed-57379ab04680",
				Name:      "Test",
				CPF:       "02815517078",
				Balance:   199.44,
				CreatedAt: time.Time{}.String(),
			},
		},
		{
			name: "Create account fails due to repository error",
			args: args{
				input: CreateAccountInput{
					Name:    "Test",
					CPF:     "02815517078",
					Balance: 19944,
				},
			},
			repository: mockAccountRepoStore{
				result: domain.Account{},
				err:    errors.New("repository error"),
			},
			presenter: mockCreateAccountPresenter{
				result: CreateAccountOutput{},
			},
			expectedError: "repository error",
			expected:      CreateAccountOutput{},
		},
		{
			name: "Create account with empty name",
			args: args{
				input: CreateAccountInput{
					Name:    "",
					CPF:     "02815517078",
					Balance: 19944,
				},
			},
			repository: mockAccountRepoStore{
				result: domain.Account{},
				err:    errors.New("invalid input"),
			},
			presenter: mockCreateAccountPresenter{
				result: CreateAccountOutput{},
			},
			expectedError: "invalid input",
			expected:      CreateAccountOutput{},
		},
		{
			name: "Create account with invalid CPF",
			args: args{
				input: CreateAccountInput{
					Name:    "Test",
					CPF:     "invalid_cpf",
					Balance: 19944,
				},
			},
			repository: mockAccountRepoStore{
				result: domain.Account{},
				err:    errors.New("invalid CPF"),
			},
			presenter: mockCreateAccountPresenter{
				result: CreateAccountOutput{},
			},
			expectedError: "invalid CPF",
			expected:      CreateAccountOutput{},
		},
		{
			name: "Create account with zero balance",
			args: args{
				input: CreateAccountInput{
					Name:    "Test",
					CPF:     "02815517078",
					Balance: 0,
				},
			},
			repository: mockAccountRepoStore{
				result: domain.Account{},
				err:    errors.New("balance must be greater than zero"),
			},
			presenter: mockCreateAccountPresenter{
				result: CreateAccountOutput{},
			},
			expectedError: "balance must be greater than zero",
			expected:      CreateAccountOutput{},
		},
		{
			name: "Create account timeout",
			args: args{
				input: CreateAccountInput{
					Name:    "Test",
					CPF:     "02815517078",
					Balance: 19944,
				},
			},
			repository: mockAccountRepoStore{
				result: domain.Account{},
				err:    context.DeadlineExceeded,
			},
			presenter: mockCreateAccountPresenter{
				result: CreateAccountOutput{},
			},
			expectedError: context.DeadlineExceeded.Error(),
			expected:      CreateAccountOutput{},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			uc := NewCreateAccountInteractor(tt.repository, tt.presenter, time.Millisecond)
			ctx, cancel := context.WithTimeout(context.Background(), time.Millisecond)
			defer cancel()

			result, err := uc.Execute(ctx, tt.args.input)
			if (err != nil) && (err.Error() != tt.expectedError) {
				t.Errorf("[TestCase '%s'] Result: '%v' | ExpectedError: '%v'", tt.name, err, tt.expectedError)
			}
			if !reflect.DeepEqual(result, tt.expected) {
				t.Errorf("[TestCase '%s'] Result: '%v' | Expected: '%v'", tt.name, result, tt.expected)
			}
		})
	}
}

// Mock implementations
type mockAccountRepoStore struct {
	domain.AccountRepository

	result domain.Account
	err    error
}

func (m mockAccountRepoStore) Create(ctx context.Context, account domain.Account) (domain.Account, error) {
	return m.result, m.err
}

type mockCreateAccountPresenter struct {
	result CreateAccountOutput
}

func (m mockCreateAccountPresenter) Output(account domain.Account) CreateAccountOutput {
	return m.result
}

// NewCreateAccountInteractor creates a new instance of createAccountInteractor
func NewCreateAccountInteractor(repo domain.AccountRepository, presenter CreateAccountPresenter, timeout time.Duration) CreateAccountUseCase {
	return &createAccountInteractor{
		repo:       repo,
		presenter:  presenter,
		ctxTimeout: timeout,
	}
}
