// ********RoostGPT********
/*
Test generated by RoostGPT for test mayankzbio-go-clean using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=NewCreateAccountInteractor_d2c0918d57
ROOST_METHOD_SIG_HASH=NewCreateAccountInteractor_c6949d3abe

FUNCTION_DEF=func NewCreateAccountInteractor(repo domain.AccountRepository, presenter CreateAccountPresenter, t time.Duration) CreateAccountUseCase // NewCreateAccountInteractor creates new createAccountInteractor with its dependencies

Existing Test Information:
These test cases are already implemented and not included for test generation scenario:
File: go-clean-architecture/usecase/create_account_test.go
Test Cases:
    [TestCreateAccountInteractor_Execute]

```
Scenario 1: Successful Creation of Account with Valid Input

Details:
  Description: This test checks the successful creation of an account when valid input data is provided. It ensures that the interactor correctly processes the input and returns the expected output.
Execution:
  Arrange: Set up a mock repository that simulates successful account creation and a mock presenter that formats the output. Use valid input data for account creation.
  Act: Call the `NewCreateAccountInteractor` function with the mock repository, presenter, and a valid timeout duration.
  Assert: Verify that the returned `CreateAccountUseCase` is not nil and that the `Execute` method returns the expected `CreateAccountOutput` without errors.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The test asserts that the interactor correctly initializes and processes valid input, returning the expected output. This is crucial for ensuring that the account creation functionality works as intended in normal conditions.

Scenario 2: Handling of Repository Error During Account Creation

Details:
  Description: This test checks the behavior of the interactor when the repository returns an error during account creation. It ensures that the interactor correctly propagates the error.
Execution:
  Arrange: Set up a mock repository that simulates an error during account creation and a mock presenter. Use valid input data for account creation.
  Act: Call the `NewCreateAccountInteractor` function with the mock repository, presenter, and a valid timeout duration.
  Assert: Verify that the `Execute` method returns an error and that the error message matches the expected error from the repository.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The test asserts that the interactor correctly handles repository errors, which is important for robust error handling and user feedback in the application.

Scenario 3: Timeout Handling During Account Creation

Details:
  Description: This test checks the behavior of the interactor when the operation exceeds the specified timeout duration. It ensures that the interactor correctly handles timeouts.
Execution:
  Arrange: Set up a mock repository and presenter. Use valid input data for account creation and set a very short timeout duration.
  Act: Call the `NewCreateAccountInteractor` function with the mock repository, presenter, and the short timeout duration.
  Assert: Verify that the `Execute` method returns an error indicating a timeout.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The test asserts that the interactor respects the timeout setting, which is crucial for maintaining application performance and responsiveness.

Scenario 4: Invalid Input Data for Account Creation

Details:
  Description: This test checks the behavior of the interactor when invalid input data is provided. It ensures that the interactor correctly handles input validation errors.
Execution:
  Arrange: Set up a mock repository and presenter. Use invalid input data for account creation, such as missing required fields or invalid values.
  Act: Call the `NewCreateAccountInteractor` function with the mock repository, presenter, and a valid timeout duration.
  Assert: Verify that the `Execute` method returns an error indicating invalid input.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The test asserts that the interactor correctly validates input data, which is important for ensuring data integrity and preventing erroneous operations.

Scenario 5: Successful Account Creation with Edge Case Input

Details:
  Description: This test checks the successful creation of an account when edge case input data is provided, such as minimum valid balance. It ensures that the interactor handles edge cases correctly.
Execution:
  Arrange: Set up a mock repository and presenter. Use edge case input data for account creation, such as the minimum valid balance.
  Act: Call the `NewCreateAccountInteractor` function with the mock repository, presenter, and a valid timeout duration.
  Assert: Verify that the `Execute` method returns the expected `CreateAccountOutput` without errors.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The test asserts that the interactor correctly processes edge case input, which is important for ensuring the robustness of the account creation functionality across a range of valid inputs.
```
*/

// ********RoostGPT********

package usecase

import (
	"context"
	"errors"
	"reflect"
	"testing"
	"time"

	"github.com/gsabadini/go-clean-architecture/domain"
)

func TestNewCreateAccountInteractor(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name          string
		repository    domain.AccountRepository
		presenter     CreateAccountPresenter
		timeout       time.Duration
		input         CreateAccountInput
		expected      CreateAccountOutput
		expectedError string
	}{
		{
			name: "Scenario 1: Successful Creation of Account with Valid Input",
			repository: mockAccountRepoStore{
				result: domain.NewAccount("1", "John Doe", "12345678900", 10000, time.Now()),
				err:    nil,
			},
			presenter: mockCreateAccountPresenter{
				result: CreateAccountOutput{
					ID:      "1",
					Name:    "John Doe",
					CPF:     "12345678900",
					Balance: 100.00,
				},
			},
			timeout: time.Second,
			input: CreateAccountInput{
				Name:    "John Doe",
				CPF:     "12345678900",
				Balance: 10000,
			},
			expected: CreateAccountOutput{
				ID:      "1",
				Name:    "John Doe",
				CPF:     "12345678900",
				Balance: 100.00,
			},
			expectedError: "",
		},
		{
			name: "Scenario 2: Handling of Repository Error During Account Creation",
			repository: mockAccountRepoStore{
				result: domain.Account{},
				err:    errors.New("repository error"),
			},
			presenter: mockCreateAccountPresenter{
				result: CreateAccountOutput{},
			},
			timeout: time.Second,
			input: CreateAccountInput{
				Name:    "John Doe",
				CPF:     "12345678900",
				Balance: 10000,
			},
			expected:      CreateAccountOutput{},
			expectedError: "repository error",
		},
		{
			name: "Scenario 3: Timeout Handling During Account Creation",
			repository: mockAccountRepoStore{
				result: domain.Account{},
				err:    nil,
			},
			presenter: mockCreateAccountPresenter{
				result: CreateAccountOutput{},
			},
			timeout: time.Nanosecond,
			input: CreateAccountInput{
				Name:    "John Doe",
				CPF:     "12345678900",
				Balance: 10000,
			},
			expected:      CreateAccountOutput{},
			expectedError: "context deadline exceeded",
		},
		{
			name: "Scenario 4: Invalid Input Data for Account Creation",
			repository: mockAccountRepoStore{
				result: domain.Account{},
				err:    nil,
			},
			presenter: mockCreateAccountPresenter{
				result: CreateAccountOutput{},
			},
			timeout: time.Second,
			input: CreateAccountInput{
				Name:    "",
				CPF:     "",
				Balance: 0,
			},
			expected:      CreateAccountOutput{},
			expectedError: "invalid input",
		},
		{
			name: "Scenario 5: Successful Account Creation with Edge Case Input",
			repository: mockAccountRepoStore{
				result: domain.NewAccount("2", "Jane Doe", "09876543211", 1, time.Now()),
				err:    nil,
			},
			presenter: mockCreateAccountPresenter{
				result: CreateAccountOutput{
					ID:      "2",
					Name:    "Jane Doe",
					CPF:     "09876543211",
					Balance: 0.01,
				},
			},
			timeout: time.Second,
			input: CreateAccountInput{
				Name:    "Jane Doe",
				CPF:     "09876543211",
				Balance: 1,
			},
			expected: CreateAccountOutput{
				ID:      "2",
				Name:    "Jane Doe",
				CPF:     "09876543211",
				Balance: 0.01,
			},
			expectedError: "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			uc := NewCreateAccountInteractor(tt.repository, tt.presenter, tt.timeout)
			result, err := uc.Execute(context.Background(), tt.input)

			if err != nil && err.Error() != tt.expectedError {
				t.Errorf("Expected error: %v, got: %v", tt.expectedError, err)
			}

			if err == nil && tt.expectedError != "" {
				t.Errorf("Expected error: %v, got nil", tt.expectedError)
			}

			if !reflect.DeepEqual(result, tt.expected) {
				t.Errorf("Expected result: %v, got: %v", tt.expected, result)
			}
		})
	}
}
