// ********RoostGPT********
/*
Test generated by RoostGPT for test mayankzbio-go-clean using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=Account_Withdraw_28cfab335a
ROOST_METHOD_SIG_HASH=Account_Withdraw_d1473886fa

FUNCTION_DEF=func (a *Account) Withdraw(amount Money) error
Existing Test Information:
These test cases are already implemented and not included for test generation scenario:
File: go-clean-architecture/domain/account_test.go
Test Cases:
    [TestAccount_Withdraw]

```
Scenario 1: Withdraw Zero Amount

Details:
  Description: This test checks the behavior of the `Withdraw` function when the withdrawal amount is zero. It ensures that the account balance remains unchanged and no error is returned.
Execution:
  Arrange: Create an account with a positive balance.
  Act: Call the `Withdraw` method with an amount of zero.
  Assert: Verify that no error is returned and the account balance remains the same.
Validation:
  Explain the choice of assertion and the logic behind the expected result: Withdrawing zero should not affect the balance, and no error should occur.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Ensures that the function handles edge cases gracefully without unintended side effects.

Scenario 2: Withdraw Exact Balance

Details:
  Description: This test verifies that withdrawing an amount equal to the current balance is successful and results in a zero balance.
Execution:
  Arrange: Create an account with a balance of 100 units.
  Act: Call the `Withdraw` method with an amount equal to the account balance.
  Assert: Verify that no error is returned and the account balance is zero.
Validation:
  Explain the choice of assertion and the logic behind the expected result: Withdrawing the entire balance should succeed and leave the account with zero balance.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Confirms that the function correctly handles cases where the withdrawal amount matches the balance.

Scenario 3: Withdraw from Account with Minimum Balance

Details:
  Description: This test checks the behavior when attempting to withdraw from an account with the smallest possible positive balance.
Execution:
  Arrange: Create an account with a balance of 1 unit.
  Act: Call the `Withdraw` method with an amount of 1 unit.
  Assert: Verify that no error is returned and the account balance is zero.
Validation:
  Explain the choice of assertion and the logic behind the expected result: Withdrawing the entire balance should succeed, reducing the balance to zero.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Ensures that the function can handle minimal balance scenarios correctly.

Scenario 4: Withdraw with Negative Amount

Details:
  Description: This test checks the behavior of the `Withdraw` function when a negative amount is specified, which should not be allowed.
Execution:
  Arrange: Create an account with a positive balance.
  Act: Call the `Withdraw` method with a negative amount.
  Assert: Verify that an error is returned indicating invalid operation.
Validation:
  Explain the choice of assertion and the logic behind the expected result: Negative withdrawals should be invalid, and the function should return an error.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Prevents invalid operations that could lead to inconsistent account states.

Scenario 5: Withdraw from Account with Large Balance

Details:
  Description: This test verifies the function's ability to handle large balance withdrawals without errors.
Execution:
  Arrange: Create an account with a large balance.
  Act: Call the `Withdraw` method with a large amount that is less than the balance.
  Assert: Verify that no error is returned and the balance is reduced correctly.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The function should handle large numbers correctly, ensuring accurate balance updates.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Ensures robustness and correctness in handling large transactions, which is crucial for financial applications.

Scenario 6: Withdraw from Account with Maximum Integer Balance

Details:
  Description: This test checks the behavior when withdrawing from an account with the maximum possible integer balance.
Execution:
  Arrange: Create an account with the maximum integer value as balance.
  Act: Call the `Withdraw` method with a small amount.
  Assert: Verify that no error is returned and the balance is reduced by the correct amount.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The function should handle maximum integer values without overflow or errors.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Ensures the system can handle edge cases related to integer limits, preventing potential overflow issues.
```
*/

// ********RoostGPT********
package domain

import (
	"errors"
	"testing"
	"time"
)

var (
	ErrInsufficientBalance   = errors.New("insufficient balance")
	ErrInvalidWithdrawAmount = errors.New("invalid withdraw amount")
)

type Account struct {
	id        AccountID
	name      string
	cpf       string
	balance   Money
	createdAt time.Time
}

func (a *Account) Withdraw(amount Money) error {
	if amount < 0 {
		return ErrInvalidWithdrawAmount
	}
	if a.balance < amount {
		return ErrInsufficientBalance
	}
	a.balance -= amount
	return nil
}

func (a *Account) Balance() Money {
	return a.balance
}

func NewAccountBalance(balance Money) Account {
	return Account{
		id:        "test-id",
		name:      "Test Account",
		cpf:       "12345678900",
		balance:   balance,
		createdAt: time.Now(),
	}
}

func TestAccountAccountWithdraw(t *testing.T) {
	t.Parallel()
	type args struct{ amount Money }
	tests := []struct {
		name        string
		account     Account
		args        args
		expected    Money
		expectedErr error
	}{
		{
			name:        "Withdraw Zero Amount",
			args:        args{amount: 0},
			account:     NewAccountBalance(100),
			expected:    100,
			expectedErr: nil,
		},
		{
			name:        "Withdraw Exact Balance",
			args:        args{amount: 100},
			account:     NewAccountBalance(100),
			expected:    0,
			expectedErr: nil,
		},
		{
			name:        "Withdraw from Account with Minimum Balance",
			args:        args{amount: 1},
			account:     NewAccountBalance(1),
			expected:    0,
			expectedErr: nil,
		},
		{
			name:        "Withdraw with Negative Amount",
			args:        args{amount: -10},
			account:     NewAccountBalance(100),
			expectedErr: ErrInvalidWithdrawAmount,
		},
		{
			name:        "Withdraw from Account with Large Balance",
			args:        args{amount: 5000000000},
			account:     NewAccountBalance(10000000000),
			expected:    5000000000,
			expectedErr: nil,
		},
		{
			name:        "Withdraw from Account with Maximum Integer Balance",
			args:        args{amount: 1},
			account:     NewAccountBalance(Money(^uint64(0) >> 1)),
			expected:    Money(^uint64(0)>>1) - 1,
			expectedErr: nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var err error
			if err = tt.account.Withdraw(tt.args.amount); (err != nil) && (err.Error() != tt.expectedErr.Error()) {
				t.Errorf("[TestCase '%s'] ResultError: '%v' | ExpectedError: '%v'", tt.name, err, tt.expectedErr.Error())
				return
			}
			if tt.expectedErr == nil && tt.account.Balance() != tt.expected {
				t.Errorf("[TestCase '%s'] Result: '%v' | Expected: '%v'", tt.name, tt.account.Balance(), tt.expected)
			}
		})
	}
}
