// ********RoostGPT********
/*
Test generated by RoostGPT for test mayankzbio-go-clean using AI Type Open AI and AI Model gpt-4o

Test generated by RoostGPT for test mayankzbio-go-clean using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=Account_Withdraw_28cfab335a
ROOST_METHOD_SIG_HASH=Account_Withdraw_d1473886fa

FUNCTION_DEF=func (a *Account) Withdraw(amount Money) error
Existing Test Information:
These test cases are already implemented and not included for test generation scenario:
File: go-clean-architecture/domain/account_test.go
Test Cases:
    [TestAccount_Withdraw]

Here are the test scenarios for the `Account.Withdraw` function:

```
Scenario 1: Withdraw Zero Amount

Details:
  Description: This test checks the behavior of the `Withdraw` function when the amount to withdraw is zero. It ensures that the balance remains unchanged and no error is returned.
Execution:
  Arrange: Create an account with a positive balance.
  Act: Call the `Withdraw` method with an amount of zero.
  Assert: Verify that the account balance remains the same and no error is returned.
Validation:
  Explain the choice of assertion and the logic behind the expected result: Withdrawing zero should not alter the balance and should not produce an error, as it's a valid operation.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Ensures that the system can handle no-op transactions gracefully.

Scenario 2: Withdraw Exact Balance

Details:
  Description: This test verifies that withdrawing an amount equal to the current balance is successful and results in a zero balance.
Execution:
  Arrange: Create an account with a specific balance.
  Act: Call the `Withdraw` method with an amount equal to the account balance.
  Assert: Check that the account balance is zero and no error is returned.
Validation:
  Explain the choice of assertion and the logic behind the expected result: Withdrawing the entire balance should leave the account with zero balance and should not produce an error.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Confirms that the system allows users to withdraw their entire balance without issues.

Scenario 3: Withdraw from Account with Maximum Integer Balance

Details:
  Description: This test evaluates the function's behavior when withdrawing from an account with the maximum possible integer balance.
Execution:
  Arrange: Create an account with the maximum integer value as its balance.
  Act: Attempt to withdraw a small amount from the account.
  Assert: Verify that the balance is reduced correctly and no error is returned.
Validation:
  Explain the choice of assertion and the logic behind the expected result: Ensures that the function can handle large balances without overflow or errors.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Validates the system's ability to manage large financial transactions.

Scenario 4: Withdraw with Negative Amount

Details:
  Description: This test checks the function's response to an attempt to withdraw a negative amount, which should be invalid.
Execution:
  Arrange: Create an account with a positive balance.
  Act: Call the `Withdraw` method with a negative amount.
  Assert: Verify that an error is returned and the balance remains unchanged.
Validation:
  Explain the choice of assertion and the logic behind the expected result: Withdrawing a negative amount should be considered invalid and should not alter the balance.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Ensures that the system enforces valid transaction rules and prevents invalid operations.

Scenario 5: Withdraw with Insufficient Balance and Concurrent Transactions

Details:
  Description: This test examines the function's behavior when multiple concurrent withdrawals are attempted, potentially leading to insufficient balance.
Execution:
  Arrange: Create an account with a balance that is less than the sum of concurrent withdrawal attempts.
  Act: Simulate concurrent withdrawals that exceed the account balance.
  Assert: Verify that only some transactions succeed and others fail with `ErrInsufficientBalance`.
Validation:
  Explain the choice of assertion and the logic behind the expected result: Ensures that the function correctly handles concurrent access and maintains balance integrity.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Validates the system's concurrency control and data consistency mechanisms.
```

These scenarios cover a range of normal operations, edge cases, and error conditions, ensuring comprehensive testing of the `Withdraw` function's behavior.
*/

// ********RoostGPT********

package domain

import (
	"testing"
	"time"
)

func TestAccountWithdraw(t *testing.T) {
	t.Parallel()
	type args struct{ amount Money }
	tests := []struct {
		name        string
		account     Account
		args        args
		expected    Money
		expectedErr error
	}{
		{
			name:        "Withdraw Zero Amount",
			args:        args{amount: 0},
			account:     newAccountBalance(100),
			expected:    100,
			expectedErr: nil,
		},
		{
			name:        "Withdraw Exact Balance",
			args:        args{amount: 100},
			account:     newAccountBalance(100),
			expected:    0,
			expectedErr: nil,
		},
		{
			name:        "Withdraw from Account with Maximum Integer Balance",
			args:        args{amount: 1},
			account:     newAccountBalance(Money(^uint64(0) >> 1)),
			expected:    Money(^uint64(0)>>1) - 1,
			expectedErr: nil,
		},
		{
			name:        "Withdraw with Negative Amount",
			args:        args{amount: -10},
			account:     newAccountBalance(100),
			expected:    100,
			expectedErr: ErrInsufficientBalance,
		},
		{
			name:        "Withdraw with Insufficient Balance and Concurrent Transactions",
			args:        args{amount: 50},
			account:     newAccountBalance(30),
			expected:    30,
			expectedErr: ErrInsufficientBalance,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.account.Withdraw(tt.args.amount)
			if (err != nil) && (err.Error() != tt.expectedErr.Error()) {
				t.Errorf("[TestCase '%s'] ResultError: '%v' | ExpectedError: '%v'", tt.name, err, tt.expectedErr.Error())
				return
			}
			if tt.expectedErr == nil && tt.account.balance != tt.expected {
				t.Errorf("[TestCase '%s'] Result: '%v' | Expected: '%v'", tt.name, tt.account.balance, tt.expected)
			}
		})
	}
}
func newAccountBalance(balance Money) Account {
	return Account{
		id:        "test-id",
		name:      "Test Account",
		cpf:       "12345678900",
		balance:   balance,
		createdAt: time.Now(),
	}
}
