// ********RoostGPT********
/*
Test generated by RoostGPT for test go-clean-architecture using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022

ROOST_METHOD_HASH=Account.Withdraw_28cfab335a
ROOST_METHOD_SIG_HASH=Account.Withdraw_d1473886fa

FUNCTION_DEF=func (a *Account) Withdraw(amount Money) error
Existing Test Information:
These test cases are already implemented and not included for test generation scenario:
File: go-clean-architecture/domain/account_test.go
Test Cases:
    [TestAccount_Withdraw]

Scenario 1: Withdraw Zero Amount

Details:
  Description: Verify that withdrawing zero amount from an account works correctly and doesn't change the balance.
Execution:
  Arrange: Create an account with a positive balance (e.g., 1000)
  Act: Call Withdraw with amount = 0
  Assert: Verify that no error is returned and balance remains unchanged
Validation:
  This test ensures the system handles zero-value withdrawals appropriately, which is a common edge case in financial transactions.


*/

// ********RoostGPT********

package domain

import (
	"testing"
	"time"
)

func TestAccountWithdraw(t *testing.T) {
	t.Parallel()

	type args struct {
		amount Money
	}

	tests := []struct {
		name        string
		account     Account
		args        args
		expected    Money
		expectedErr error
	}{
		{
			name: "Success when withdrawing zero amount",
			account: Account{
				id:        "acc123",
				name:      "Test Account",
				cpf:       "12345678900",
				balance:   1000,
				createdAt: time.Now(),
			},
			args: args{
				amount: 0,
			},
			expected:    1000,
			expectedErr: nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.account.Withdraw(tt.args.amount)
			if (err != nil) != (tt.expectedErr != nil) {
				t.Errorf("Account.Withdraw() error = %v, expectedErr %v", err, tt.expectedErr)
				return
			}

			if tt.expectedErr == nil && tt.account.Balance() != tt.expected {
				t.Errorf("Account.Withdraw() balance = %v, expected %v", tt.account.Balance(), tt.expected)
			}
		})
	}
}
