// ********RoostGPT********
/*
Test generated by RoostGPT for test mayankzbio-go-clean using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=Money_Int64_892ac8ffdb
ROOST_METHOD_SIG_HASH=Money_Int64_6f8fb90a73

FUNCTION_DEF=func (m Money) Int64() int64
```
Scenario 1: Convert Positive Money Value to int64

Details:
  Description: This test checks the conversion of a positive Money value to an int64, ensuring that the function correctly handles typical positive values.
Execution:
  Arrange: Create a Money instance with a positive value, e.g., Money(100).
  Act: Call the Int64() method on the Money instance.
  Assert: Verify that the returned int64 value is 100.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion checks that the conversion from Money to int64 is accurate for positive values, which is a common use case.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Ensuring accurate conversion of positive monetary values is crucial for financial calculations and reporting.

Scenario 2: Convert Negative Money Value to int64

Details:
  Description: This test verifies that the function correctly converts a negative Money value to an int64, ensuring that negative values are handled properly.
Execution:
  Arrange: Create a Money instance with a negative value, e.g., Money(-50).
  Act: Call the Int64() method on the Money instance.
  Assert: Verify that the returned int64 value is -50.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion ensures that negative values are accurately converted, which is important for handling debts or refunds.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Correct handling of negative values is essential for accurate financial management and error prevention.

Scenario 3: Convert Zero Money Value to int64

Details:
  Description: This test ensures that a Money value of zero is correctly converted to an int64, verifying the function's behavior with neutral values.
Execution:
  Arrange: Create a Money instance with a value of zero, e.g., Money(0).
  Act: Call the Int64() method on the Money instance.
  Assert: Verify that the returned int64 value is 0.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion confirms that zero is correctly handled, which is important for scenarios where no transaction occurs.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Accurate handling of zero values is crucial for maintaining balance integrity and avoiding unnecessary errors.

Scenario 4: Convert Large Positive Money Value to int64

Details:
  Description: This test checks the conversion of a large positive Money value to an int64, ensuring that the function can handle large numbers without overflow.
Execution:
  Arrange: Create a Money instance with a large positive value, e.g., Money(9223372036854775807).
  Act: Call the Int64() method on the Money instance.
  Assert: Verify that the returned int64 value is 9223372036854775807.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion ensures that the function can handle the maximum int64 value, which is important for applications dealing with large financial transactions.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Handling large numbers correctly is vital for applications in high-value financial sectors.

Scenario 5: Convert Large Negative Money Value to int64

Details:
  Description: This test verifies the conversion of a large negative Money value to an int64, ensuring that the function can handle large negative numbers without overflow.
Execution:
  Arrange: Create a Money instance with a large negative value, e.g., Money(-9223372036854775808).
  Act: Call the Int64() method on the Money instance.
  Assert: Verify that the returned int64 value is -9223372036854775808.
Validation:
  Explain the choice of assertion and the logic behind the expected result: The assertion checks that the function can handle the minimum int64 value, which is crucial for applications managing large debts or losses.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Correctly handling large negative numbers is essential for financial accuracy and risk management.
```
*/

// ********RoostGPT********

package domain

import "testing"

func TestMoneyMoneyInt64(t *testing.T) {
	tests := []struct {
		name     string
		amount   Money
		expected int64
	}{
		{
			name:     "Convert Positive Money Value to int64",
			amount:   Money(100),
			expected: 100,
		},
		{
			name:     "Convert Negative Money Value to int64",
			amount:   Money(-50),
			expected: -50,
		},
		{
			name:     "Convert Zero Money Value to int64",
			amount:   Money(0),
			expected: 0,
		},
		{
			name:     "Convert Large Positive Money Value to int64",
			amount:   Money(9223372036854775807),
			expected: 9223372036854775807,
		},
		{
			name:     "Convert Large Negative Money Value to int64",
			amount:   Money(-9223372036854775808),
			expected: -9223372036854775808,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := tt.amount.Int64()
			if result != tt.expected {
				t.Errorf("Int64() = %v, want %v", result, tt.expected)
			} else {
				t.Logf("Success: %s - Int64() = %v", tt.name, result)
			}
		})
	}
}
